import type { AuditData, Theme, HealthScore, PositiveSignal } from './report-types'
import { CSS } from './report-styles'
import { renderCover, renderExecSummary } from './report-cover'
import { renderRiskMatrix, renderThemesSection, renderRoadmap } from './report-body'
import { renderPositiveSignals, renderRawFindings, renderMetadata } from './report-appendix'

const TOC_ITEMS = [
  [1, 'Cover Page'],
  [2, 'Executive Summary'],
  [3, 'Risk Matrix'],
  [4, 'Findings by Theme'],
  [5, 'Remediation Roadmap'],
  [6, "What's Working Well"],
  [7, 'Appendix — Raw Findings'],
  [8, 'Report Metadata'],
] as const

const PAGE_JS = `
<script>
function toggleTheme(id){
  var body=document.getElementById('body-'+id);
  var chv=document.getElementById('chv-'+id);
  if(!body)return;
  var isOpen=body.classList.contains('open');
  body.classList.toggle('open',!isOpen);
  if(chv)chv.textContent=isOpen?'▶':'▼';
}
// Auto-expand first card on load
window.addEventListener('DOMContentLoaded',function(){
  var first=document.querySelector('.theme-hdr');
  if(first){var id=first.parentElement&&first.parentElement.id.replace('theme-','');if(id)toggleTheme(id);}
});
</script>`

function renderToc(): string {
  const items = TOC_ITEMS.map(([n, label]) =>
    `<li><a href="#s${n}">Section ${n}: ${label}</a></li>`
  ).join('')
  return `<nav class="toc container"><h3 style="margin-bottom:.8rem">Table of Contents</h3><ol>${items}</ol></nav>`
}

export function buildReport(
  data:       AuditData,
  themes:     Theme[],
  score:      HealthScore,
  signals:    PositiveSignal[],
  aiSummary?: string,
): string {
  const body = [
    renderCover(data),
    renderToc(),
    renderExecSummary(data, themes, score, aiSummary),
    renderRiskMatrix(themes),
    renderThemesSection(themes),
    renderRoadmap(themes, data),
    renderPositiveSignals(signals),
    renderRawFindings(data),
    renderMetadata(data),
  ].join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${data.repoName} — CodeMind Audit Report</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=DM+Sans:wght@400;500;600;700&display=swap">
  <style>${CSS}</style>
</head>
<body>
${body}
<footer><div class="container">Generated by CodeMind v5.0 &nbsp;·&nbsp; ${data.generatedAt} &nbsp;·&nbsp; <a href="https://codemind.dev">codemind.dev</a></div></footer>
${PAGE_JS}
</body>
</html>`
}
